name: Generate dependency graphs
description: This re-generates the dependency graphs of each package

inputs:
  many-graphs:
    # Circumvent https://github.com/ts-graphviz/ts-graphviz/issues/1563
    # ts-graphivz uses a single `Builder` instance for all graphs generated in a given process,
    # therefore its max nodes limit is effectively a global limit, not a limit per graph.
    description: "Whether to generate the packages graphs in a single node process or several"
    required: false
    default: "false"

runs:
  using: composite

  steps:
    - name: Are we called from `main`?
      # This should only be called from the main branch of the repo.
      # If this workflow is somehow called from another branch, crash.
      if: github.ref_name != 'main'
      shell: bash
      run: |
        echo "This workflow can only be called from the main branch."
        exit 1

    - name: Generate dependency graphs (all together)
      if: inputs.many-graphs == 'false'
      shell: bash
      run: yarn generate-dependency-graphs ${{ github.workspace }}

    - name: Generate dependency graphs (one by one)
      if: inputs.many-graphs == 'true'
      shell: bash
      run: >
        yarn workspaces foreach
        --all --parallel
        --exclude "@siteimprove/alfa"
        run yarn depgraph:self

    - name: Generated global dependency graph
      if: inputs.many-graphs == 'true'
      shell: bash
      run: yarn generate-global-dependency-graph ${{ github.workspace }} global

    - name: Stage changes
      shell: bash
      # Find in current directory.
      # If the name is "node_modules", skip it, don't look inside it;
      # or
      # If the name is "dependency-graph.dot" or "dependency-graph.svg", print it with \0 separator (shell glob expansion protection)
      # Feed that list to git, through xargs to handle the \0 separator.
      run: >
        find .
        -name node_modules -prune
        -o
        -name "dependency-graph.dot" -print0
        -o
        -name "dependency-graph.svg" -print0
        | xargs -0 git add

    - name: Commit changes
      shell: bash
      # Dependency graphs may stay stable, so we allow empty commit.
      run: git commit --message="Update dependency graphs" --allow-empty
