yarnPath: .yarn/releases/yarn-2.4.0.cjs

# Opt out of Plug'n'Play as it currently requires additional configuration of
# editor SDKs for things like TypeScript and Prettier support.
# https://yarnpkg.com/configuration/yarnrc#nodeLinker
nodeLinker: node-modules
