export default {
  nestedGroups: () => [
    {
      name: "Accessibility Conformance Testing",
      children: ["@siteimprove/alfa-act", "@siteimprove/alfa-wcag"],
    },
    {
      name: "Command line",
      children: [
        "@siteimprove/alfa-cli",
        "@siteimprove/alfa-command",
        "@siteimprove/alfa-interviewer",
      ],
    },
    {
      name: "Data types",
      children: [
        "@siteimprove/alfa-affine",
        "@siteimprove/alfa-applicative",
        "@siteimprove/alfa-array",
        "@siteimprove/alfa-bits",
        "@siteimprove/alfa-branched",
        "@siteimprove/alfa-cache",
        "@siteimprove/alfa-callback",
        "@siteimprove/alfa-clone",
        "@siteimprove/alfa-collection",
        "@siteimprove/alfa-comparable",
        "@siteimprove/alfa-continuation",
        "@siteimprove/alfa-either",
        "@siteimprove/alfa-emitter",
        "@siteimprove/alfa-encoding",
        "@siteimprove/alfa-equatable",
        "@siteimprove/alfa-fnv",
        "@siteimprove/alfa-foldable",
        "@siteimprove/alfa-functor",
        "@siteimprove/alfa-future",
        "@siteimprove/alfa-generator",
        "@siteimprove/alfa-graph",
        "@siteimprove/alfa-hash",
        "@siteimprove/alfa-highlight",
        "@siteimprove/alfa-iterable",
        "@siteimprove/alfa-json",
        "@siteimprove/alfa-lazy",
        "@siteimprove/alfa-list",
        "@siteimprove/alfa-map",
        "@siteimprove/alfa-mapper",
        "@siteimprove/alfa-math",
        "@siteimprove/alfa-monad",
        "@siteimprove/alfa-network",
        "@siteimprove/alfa-option",
        "@siteimprove/alfa-parser",
        "@siteimprove/alfa-performance",
        "@siteimprove/alfa-predicate",
        "@siteimprove/alfa-promise",
        "@siteimprove/alfa-record",
        "@siteimprove/alfa-reducer",
        "@siteimprove/alfa-refinement",
        "@siteimprove/alfa-result",
        "@siteimprove/alfa-selective",
        "@siteimprove/alfa-sequence",
        "@siteimprove/alfa-set",
        "@siteimprove/alfa-slice",
        "@siteimprove/alfa-test",
        "@siteimprove/alfa-thenable",
        "@siteimprove/alfa-thunk",
        "@siteimprove/alfa-time",
        "@siteimprove/alfa-trampoline",
        "@siteimprove/alfa-trilean",
        "@siteimprove/alfa-tuple",
      ],
    },
    {
      name: "Integrations with test frameworks",
      children: [
        "@siteimprove/alfa-assert",
        "@siteimprove/alfa-chai",
        "@siteimprove/alfa-cypress",
        "@siteimprove/alfa-jasmine",
        "@siteimprove/alfa-jest",
        "@siteimprove/alfa-unexpected",
        "@siteimprove/alfa-angular",
        "@siteimprove/alfa-cheerio",
        "@siteimprove/alfa-enzyme",
        "@siteimprove/alfa-jquery",
        "@siteimprove/alfa-playwright",
        "@siteimprove/alfa-protractor",
        "@siteimprove/alfa-puppeteer",
        "@siteimprove/alfa-react",
        "@siteimprove/alfa-vue",
        "@siteimprove/alfa-webdriver",
      ],
    },
    {
      name: "Serialization",
      children: [
        "@siteimprove/alfa-earl",
        "@siteimprove/alfa-formatter",
        "@siteimprove/alfa-formatter-earl",
        "@siteimprove/alfa-formatter-json",
        "@siteimprove/alfa-formatter-sarif",
        "@siteimprove/alfa-json-ld",
        "@siteimprove/alfa-sarif",
      ],
    },
    {
      name: "Understanding the web",
      children: [
        "@siteimprove/alfa-aria",
        "@siteimprove/alfa-cascade",
        "@siteimprove/alfa-compatibility",
        "@siteimprove/alfa-css",
        "@siteimprove/alfa-device",
        "@siteimprove/alfa-dom",
        "@siteimprove/alfa-http",
        "@siteimprove/alfa-iana",
        "@siteimprove/alfa-media",
        "@siteimprove/alfa-selector",
        "@siteimprove/alfa-style",
        "@siteimprove/alfa-table",
        "@siteimprove/alfa-url",
        "@siteimprove/alfa-web",
        "@siteimprove/alfa-xpath",
      ],
    },
    {
      name: "Web crawler",
      children: [
        "@siteimprove/alfa-crawler",
        "@siteimprove/alfa-frontier",
        "@siteimprove/alfa-scraper",
      ],
    },
    {
      name: "a super group name",
      children: [
        {
          name: "a group name",
          children: [
            "package 1",
            "package 2",
            {
              name: "a sub group name",
              children: ["package 3"],
            },
          ],
        },
        "package 4",
      ],
    },
  ],
};
