// This file has been automatically generated based on the WAI-ARIA specification.
// Do therefore not modify it directly! If you wish to make changes, do so in
// `scripts/attributes.js` and run `yarn generate` to rebuild this file.

export type Attributes = typeof Attributes;

export const Attributes = {
  "aria-activedescendant": {
    index: 0,
    kind: "property",
    type: "id-reference",
    options: null,
    default: null,
  },
  "aria-atomic": {
    index: 1,
    kind: "property",
    type: "true-false",
    options: null,
    default: "false",
  },
  "aria-autocomplete": {
    index: 2,
    kind: "property",
    type: "token",
    options: ["inline", "list", "both", "none"],
    default: "none",
  },
  "aria-busy": {
    index: 3,
    kind: "state",
    type: "true-false",
    options: null,
    default: "false",
  },
  "aria-checked": {
    index: 4,
    kind: "state",
    type: "tristate",
    options: null,
    default: "undefined",
  },
  "aria-colcount": {
    index: 5,
    kind: "property",
    type: "integer",
    options: null,
    default: null,
  },
  "aria-colindex": {
    index: 6,
    kind: "property",
    type: "integer",
    options: null,
    default: null,
  },
  "aria-colspan": {
    index: 7,
    kind: "property",
    type: "integer",
    options: null,
    default: null,
  },
  "aria-controls": {
    index: 8,
    kind: "property",
    type: "id-reference-list",
    options: null,
    default: null,
  },
  "aria-current": {
    index: 9,
    kind: "state",
    type: "token",
    options: ["page", "step", "location", "date", "time", "true", "false"],
    default: "false",
  },
  "aria-describedby": {
    index: 10,
    kind: "property",
    type: "id-reference-list",
    options: null,
    default: null,
  },
  "aria-details": {
    index: 11,
    kind: "property",
    type: "id-reference",
    options: null,
    default: null,
  },
  "aria-disabled": {
    index: 12,
    kind: "state",
    type: "true-false",
    options: null,
    default: "false",
  },
  "aria-dropeffect": {
    index: 13,
    kind: "property",
    type: "token-list",
    options: ["copy", "execute", "link", "move", "none", "popup"],
    default: "none",
  },
  "aria-errormessage": {
    index: 14,
    kind: "property",
    type: "id-reference",
    options: null,
    default: null,
  },
  "aria-expanded": {
    index: 15,
    kind: "state",
    type: "true-false-undefined",
    options: null,
    default: "undefined",
  },
  "aria-flowto": {
    index: 16,
    kind: "property",
    type: "id-reference-list",
    options: null,
    default: null,
  },
  "aria-grabbed": {
    index: 17,
    kind: "state",
    type: "true-false-undefined",
    options: null,
    default: "undefined",
  },
  "aria-haspopup": {
    index: 18,
    kind: "property",
    type: "token",
    options: ["false", "true", "menu", "listbox", "tree", "grid", "dialog"],
    default: "false",
  },
  "aria-hidden": {
    index: 19,
    kind: "state",
    type: "true-false-undefined",
    options: null,
    default: "undefined",
  },
  "aria-invalid": {
    index: 20,
    kind: "state",
    type: "token",
    options: ["grammar", "false", "spelling", "true"],
    default: "false",
  },
  "aria-keyshortcuts": {
    index: 21,
    kind: "property",
    type: "string",
    options: null,
    default: null,
  },
  "aria-label": {
    index: 22,
    kind: "property",
    type: "string",
    options: null,
    default: null,
  },
  "aria-labelledby": {
    index: 23,
    kind: "property",
    type: "id-reference-list",
    options: null,
    default: null,
  },
  "aria-level": {
    index: 24,
    kind: "property",
    type: "integer",
    options: null,
    default: null,
  },
  "aria-live": {
    index: 25,
    kind: "property",
    type: "token",
    options: ["assertive", "off", "polite"],
    default: "off",
  },
  "aria-modal": {
    index: 26,
    kind: "property",
    type: "true-false",
    options: null,
    default: "false",
  },
  "aria-multiline": {
    index: 27,
    kind: "property",
    type: "true-false",
    options: null,
    default: "false",
  },
  "aria-multiselectable": {
    index: 28,
    kind: "property",
    type: "true-false",
    options: null,
    default: "false",
  },
  "aria-orientation": {
    index: 29,
    kind: "property",
    type: "token",
    options: ["horizontal", "undefined", "vertical"],
    default: "undefined",
  },
  "aria-owns": {
    index: 30,
    kind: "property",
    type: "id-reference-list",
    options: null,
    default: null,
  },
  "aria-placeholder": {
    index: 31,
    kind: "property",
    type: "string",
    options: null,
    default: null,
  },
  "aria-posinset": {
    index: 32,
    kind: "property",
    type: "integer",
    options: null,
    default: null,
  },
  "aria-pressed": {
    index: 33,
    kind: "state",
    type: "tristate",
    options: null,
    default: "undefined",
  },
  "aria-readonly": {
    index: 34,
    kind: "property",
    type: "true-false",
    options: null,
    default: "false",
  },
  "aria-relevant": {
    index: 35,
    kind: "property",
    type: "token-list",
    options: ["additions", "additions text", "all", "removals", "text"],
    default: "additions text",
  },
  "aria-required": {
    index: 36,
    kind: "property",
    type: "true-false",
    options: null,
    default: "false",
  },
  "aria-roledescription": {
    index: 37,
    kind: "property",
    type: "string",
    options: null,
    default: null,
  },
  "aria-rowcount": {
    index: 38,
    kind: "property",
    type: "integer",
    options: null,
    default: null,
  },
  "aria-rowindex": {
    index: 39,
    kind: "property",
    type: "integer",
    options: null,
    default: null,
  },
  "aria-rowspan": {
    index: 40,
    kind: "property",
    type: "integer",
    options: null,
    default: null,
  },
  "aria-selected": {
    index: 41,
    kind: "state",
    type: "true-false-undefined",
    options: null,
    default: "undefined",
  },
  "aria-setsize": {
    index: 42,
    kind: "property",
    type: "integer",
    options: null,
    default: null,
  },
  "aria-sort": {
    index: 43,
    kind: "property",
    type: "token",
    options: ["ascending", "descending", "none", "other"],
    default: "none",
  },
  "aria-valuemax": {
    index: 44,
    kind: "property",
    type: "number",
    options: null,
    default: null,
  },
  "aria-valuemin": {
    index: 45,
    kind: "property",
    type: "number",
    options: null,
    default: null,
  },
  "aria-valuenow": {
    index: 46,
    kind: "property",
    type: "number",
    options: null,
    default: null,
  },
  "aria-valuetext": {
    index: 47,
    kind: "property",
    type: "string",
    options: null,
    default: null,
  },
} as const;
