// This file has been automatically generated based on the WCAG specification.
// Do therefore not modify it directly! If you wish to make changes, do so in
// `scripts/criteria.js` and run `yarn generate` to rebuild this file.

export type Criteria = typeof Criteria;

export const Criteria = {
  "1.1.1": {
    index: 0,
    uri: "https://www.w3.org/TR/WCAG/#non-text-content",
    title: "Non-text Content",
    level: "A",
  },
  "1.2.1": {
    index: 1,
    uri: "https://www.w3.org/TR/WCAG/#audio-only-and-video-only-prerecorded",
    title: "Audio-only and Video-only (Prerecorded)",
    level: "A",
  },
  "1.2.2": {
    index: 2,
    uri: "https://www.w3.org/TR/WCAG/#captions-prerecorded",
    title: "Captions (Prerecorded)",
    level: "A",
  },
  "1.2.3": {
    index: 3,
    uri:
      "https://www.w3.org/TR/WCAG/#audio-description-or-media-alternative-prerecorded",
    title: "Audio Description or Media Alternative (Prerecorded)",
    level: "A",
  },
  "1.2.4": {
    index: 4,
    uri: "https://www.w3.org/TR/WCAG/#captions-live",
    title: "Captions (Live)",
    level: "AA",
  },
  "1.2.5": {
    index: 5,
    uri: "https://www.w3.org/TR/WCAG/#audio-description-prerecorded",
    title: "Audio Description (Prerecorded)",
    level: "AA",
  },
  "1.2.6": {
    index: 6,
    uri: "https://www.w3.org/TR/WCAG/#sign-language-prerecorded",
    title: "Sign Language (Prerecorded)",
    level: "AAA",
  },
  "1.2.7": {
    index: 7,
    uri: "https://www.w3.org/TR/WCAG/#extended-audio-description-prerecorded",
    title: "Extended Audio Description (Prerecorded)",
    level: "AAA",
  },
  "1.2.8": {
    index: 8,
    uri: "https://www.w3.org/TR/WCAG/#media-alternative-prerecorded",
    title: "Media Alternative (Prerecorded)",
    level: "AAA",
  },
  "1.2.9": {
    index: 9,
    uri: "https://www.w3.org/TR/WCAG/#audio-only-live",
    title: "Audio-only (Live)",
    level: "AAA",
  },
  "1.3.1": {
    index: 10,
    uri: "https://www.w3.org/TR/WCAG/#info-and-relationships",
    title: "Info and Relationships",
    level: "A",
  },
  "1.3.2": {
    index: 11,
    uri: "https://www.w3.org/TR/WCAG/#meaningful-sequence",
    title: "Meaningful Sequence",
    level: "A",
  },
  "1.3.3": {
    index: 12,
    uri: "https://www.w3.org/TR/WCAG/#sensory-characteristics",
    title: "Sensory Characteristics",
    level: "A",
  },
  "1.3.4": {
    index: 13,
    uri: "https://www.w3.org/TR/WCAG/#orientation",
    title: "Orientation",
    level: "AA",
  },
  "1.3.5": {
    index: 14,
    uri: "https://www.w3.org/TR/WCAG/#identify-input-purpose",
    title: "Identify Input Purpose",
    level: "AA",
  },
  "1.3.6": {
    index: 15,
    uri: "https://www.w3.org/TR/WCAG/#identify-purpose",
    title: "Identify Purpose",
    level: "AAA",
  },
  "1.4.1": {
    index: 16,
    uri: "https://www.w3.org/TR/WCAG/#use-of-color",
    title: "Use of Color",
    level: "A",
  },
  "1.4.2": {
    index: 17,
    uri: "https://www.w3.org/TR/WCAG/#audio-control",
    title: "Audio Control",
    level: "A",
  },
  "1.4.3": {
    index: 18,
    uri: "https://www.w3.org/TR/WCAG/#contrast-minimum",
    title: "Contrast (Minimum)",
    level: "AA",
  },
  "1.4.4": {
    index: 19,
    uri: "https://www.w3.org/TR/WCAG/#resize-text",
    title: "Resize text",
    level: "AA",
  },
  "1.4.5": {
    index: 20,
    uri: "https://www.w3.org/TR/WCAG/#images-of-text",
    title: "Images of Text",
    level: "AA",
  },
  "1.4.6": {
    index: 21,
    uri: "https://www.w3.org/TR/WCAG/#contrast-enhanced",
    title: "Contrast (Enhanced)",
    level: "AAA",
  },
  "1.4.7": {
    index: 22,
    uri: "https://www.w3.org/TR/WCAG/#low-or-no-background-audio",
    title: "Low or No Background Audio",
    level: "AAA",
  },
  "1.4.8": {
    index: 23,
    uri: "https://www.w3.org/TR/WCAG/#visual-presentation",
    title: "Visual Presentation",
    level: "AAA",
  },
  "1.4.9": {
    index: 24,
    uri: "https://www.w3.org/TR/WCAG/#images-of-text-no-exception",
    title: "Images of Text (No Exception)",
    level: "AAA",
  },
  "1.4.10": {
    index: 25,
    uri: "https://www.w3.org/TR/WCAG/#reflow",
    title: "Reflow",
    level: "AA",
  },
  "1.4.11": {
    index: 26,
    uri: "https://www.w3.org/TR/WCAG/#non-text-contrast",
    title: "Non-text Contrast",
    level: "AA",
  },
  "1.4.12": {
    index: 27,
    uri: "https://www.w3.org/TR/WCAG/#text-spacing",
    title: "Text Spacing",
    level: "AA",
  },
  "1.4.13": {
    index: 28,
    uri: "https://www.w3.org/TR/WCAG/#content-on-hover-or-focus",
    title: "Content on Hover or Focus",
    level: "AA",
  },
  "2.1.1": {
    index: 29,
    uri: "https://www.w3.org/TR/WCAG/#keyboard",
    title: "Keyboard",
    level: "A",
  },
  "2.1.2": {
    index: 30,
    uri: "https://www.w3.org/TR/WCAG/#no-keyboard-trap",
    title: "No Keyboard Trap",
    level: "A",
  },
  "2.1.3": {
    index: 31,
    uri: "https://www.w3.org/TR/WCAG/#keyboard-no-exception",
    title: "Keyboard (No Exception)",
    level: "AAA",
  },
  "2.1.4": {
    index: 32,
    uri: "https://www.w3.org/TR/WCAG/#character-key-shortcuts",
    title: "Character Key Shortcuts",
    level: "A",
  },
  "2.2.1": {
    index: 33,
    uri: "https://www.w3.org/TR/WCAG/#timing-adjustable",
    title: "Timing Adjustable",
    level: "A",
  },
  "2.2.2": {
    index: 34,
    uri: "https://www.w3.org/TR/WCAG/#pause-stop-hide",
    title: "Pause, Stop, Hide",
    level: "A",
  },
  "2.2.3": {
    index: 35,
    uri: "https://www.w3.org/TR/WCAG/#no-timing",
    title: "No Timing",
    level: "AAA",
  },
  "2.2.4": {
    index: 36,
    uri: "https://www.w3.org/TR/WCAG/#interruptions",
    title: "Interruptions",
    level: "AAA",
  },
  "2.2.5": {
    index: 37,
    uri: "https://www.w3.org/TR/WCAG/#re-authenticating",
    title: "Re-authenticating",
    level: "AAA",
  },
  "2.2.6": {
    index: 38,
    uri: "https://www.w3.org/TR/WCAG/#timeouts",
    title: "Timeouts",
    level: "AAA",
  },
  "2.3.1": {
    index: 39,
    uri: "https://www.w3.org/TR/WCAG/#three-flashes-or-below-threshold",
    title: "Three Flashes or Below Threshold",
    level: "A",
  },
  "2.3.2": {
    index: 40,
    uri: "https://www.w3.org/TR/WCAG/#three-flashes",
    title: "Three Flashes",
    level: "AAA",
  },
  "2.3.3": {
    index: 41,
    uri: "https://www.w3.org/TR/WCAG/#animation-from-interactions",
    title: "Animation from Interactions",
    level: "AAA",
  },
  "2.4.1": {
    index: 42,
    uri: "https://www.w3.org/TR/WCAG/#bypass-blocks",
    title: "Bypass Blocks",
    level: "A",
  },
  "2.4.2": {
    index: 43,
    uri: "https://www.w3.org/TR/WCAG/#page-titled",
    title: "Page Titled",
    level: "A",
  },
  "2.4.3": {
    index: 44,
    uri: "https://www.w3.org/TR/WCAG/#focus-order",
    title: "Focus Order",
    level: "A",
  },
  "2.4.4": {
    index: 45,
    uri: "https://www.w3.org/TR/WCAG/#link-purpose-in-context",
    title: "Link Purpose (In Context)",
    level: "A",
  },
  "2.4.5": {
    index: 46,
    uri: "https://www.w3.org/TR/WCAG/#multiple-ways",
    title: "Multiple Ways",
    level: "AA",
  },
  "2.4.6": {
    index: 47,
    uri: "https://www.w3.org/TR/WCAG/#headings-and-labels",
    title: "Headings and Labels",
    level: "AA",
  },
  "2.4.7": {
    index: 48,
    uri: "https://www.w3.org/TR/WCAG/#focus-visible",
    title: "Focus Visible",
    level: "AA",
  },
  "2.4.8": {
    index: 49,
    uri: "https://www.w3.org/TR/WCAG/#location",
    title: "Location",
    level: "AAA",
  },
  "2.4.9": {
    index: 50,
    uri: "https://www.w3.org/TR/WCAG/#link-purpose-link-only",
    title: "Link Purpose (Link Only)",
    level: "AAA",
  },
  "2.4.10": {
    index: 51,
    uri: "https://www.w3.org/TR/WCAG/#section-headings",
    title: "Section Headings",
    level: "AAA",
  },
  "2.5.1": {
    index: 52,
    uri: "https://www.w3.org/TR/WCAG/#pointer-gestures",
    title: "Pointer Gestures",
    level: "A",
  },
  "2.5.2": {
    index: 53,
    uri: "https://www.w3.org/TR/WCAG/#pointer-cancellation",
    title: "Pointer Cancellation",
    level: "A",
  },
  "2.5.3": {
    index: 54,
    uri: "https://www.w3.org/TR/WCAG/#label-in-name",
    title: "Label in Name",
    level: "A",
  },
  "2.5.4": {
    index: 55,
    uri: "https://www.w3.org/TR/WCAG/#motion-actuation",
    title: "Motion Actuation",
    level: "A",
  },
  "2.5.5": {
    index: 56,
    uri: "https://www.w3.org/TR/WCAG/#target-size",
    title: "Target Size",
    level: "AAA",
  },
  "2.5.6": {
    index: 57,
    uri: "https://www.w3.org/TR/WCAG/#concurrent-input-mechanisms",
    title: "Concurrent Input Mechanisms",
    level: "AAA",
  },
  "3.1.1": {
    index: 58,
    uri: "https://www.w3.org/TR/WCAG/#language-of-page",
    title: "Language of Page",
    level: "A",
  },
  "3.1.2": {
    index: 59,
    uri: "https://www.w3.org/TR/WCAG/#language-of-parts",
    title: "Language of Parts",
    level: "AA",
  },
  "3.1.3": {
    index: 60,
    uri: "https://www.w3.org/TR/WCAG/#unusual-words",
    title: "Unusual Words",
    level: "AAA",
  },
  "3.1.4": {
    index: 61,
    uri: "https://www.w3.org/TR/WCAG/#abbreviations",
    title: "Abbreviations",
    level: "AAA",
  },
  "3.1.5": {
    index: 62,
    uri: "https://www.w3.org/TR/WCAG/#reading-level",
    title: "Reading Level",
    level: "AAA",
  },
  "3.1.6": {
    index: 63,
    uri: "https://www.w3.org/TR/WCAG/#pronunciation",
    title: "Pronunciation",
    level: "AAA",
  },
  "3.2.1": {
    index: 64,
    uri: "https://www.w3.org/TR/WCAG/#on-focus",
    title: "On Focus",
    level: "A",
  },
  "3.2.2": {
    index: 65,
    uri: "https://www.w3.org/TR/WCAG/#on-input",
    title: "On Input",
    level: "A",
  },
  "3.2.3": {
    index: 66,
    uri: "https://www.w3.org/TR/WCAG/#consistent-navigation",
    title: "Consistent Navigation",
    level: "AA",
  },
  "3.2.4": {
    index: 67,
    uri: "https://www.w3.org/TR/WCAG/#consistent-identification",
    title: "Consistent Identification",
    level: "AA",
  },
  "3.2.5": {
    index: 68,
    uri: "https://www.w3.org/TR/WCAG/#change-on-request",
    title: "Change on Request",
    level: "AAA",
  },
  "3.3.1": {
    index: 69,
    uri: "https://www.w3.org/TR/WCAG/#error-identification",
    title: "Error Identification",
    level: "A",
  },
  "3.3.2": {
    index: 70,
    uri: "https://www.w3.org/TR/WCAG/#labels-or-instructions",
    title: "Labels or Instructions",
    level: "A",
  },
  "3.3.3": {
    index: 71,
    uri: "https://www.w3.org/TR/WCAG/#error-suggestion",
    title: "Error Suggestion",
    level: "AA",
  },
  "3.3.4": {
    index: 72,
    uri: "https://www.w3.org/TR/WCAG/#error-prevention-legal-financial-data",
    title: "Error Prevention (Legal, Financial, Data)",
    level: "AA",
  },
  "3.3.5": {
    index: 73,
    uri: "https://www.w3.org/TR/WCAG/#help",
    title: "Help",
    level: "AAA",
  },
  "3.3.6": {
    index: 74,
    uri: "https://www.w3.org/TR/WCAG/#error-prevention-all",
    title: "Error Prevention (All)",
    level: "AAA",
  },
  "4.1.1": {
    index: 75,
    uri: "https://www.w3.org/TR/WCAG/#parsing",
    title: "Parsing",
    level: "A",
  },
  "4.1.2": {
    index: 76,
    uri: "https://www.w3.org/TR/WCAG/#name-role-value",
    title: "Name, Role, Value",
    level: "A",
  },
  "4.1.3": {
    index: 77,
    uri: "https://www.w3.org/TR/WCAG/#status-messages",
    title: "Status Messages",
    level: "AA",
  },
} as const;
