name: Generate documentation
description: This re-generates the API documentation and pushes it.

runs:
  using: composite
  steps:
    - name: Are we called from `main`?
      # This should only be called from the main branch of the repo.
      # If this workflow is somehow called from another branch, crash.
      if: github.ref_name != 'main'
      run: |
        echo "This workflow can only be called from the main branch."
        exit 1

    - name: Extract API documentation
      run: yarn extract

    - name: Generate text documentation
      run: yarn document

    - name: Commit and push changes
      run: |
        git add docs/api
        git commit --message="Update API documentation"
        git push
