name: Integrate

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  merge_group:
    types: [checks_requested]

concurrency:
  group: integrate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # 22 is in Maintenance until April 2027.
        # 24 is Active until October 2026, Maintenance until April 2028.
        # 26 is Current from May 2026 to October 2026, then Active until October 2027, Maintenance until April 2029.
        # 28 will be Current in April/May 2027.
        # https://nodejs.org/en/about/previous-releases
        node: [22, 24, 26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install --immutable
      - run: yarn dedupe --check
      - run: yarn build --quiet
      - run: yarn coverage --coverage.reporter=text-summary --coverage.thresholds.lines=75
      - run: yarn validate-structure ${{ github.workspace }}
      - run: yarn extract --quiet
      - run: yarn knip
